[workspace]
members = [ "crates/unbricked", "crates/conc_adder","crates/guessing_game", "crates/sudoku_solver", "crates/sysinfo_cli", "crates/temp", "crates/tiny_shell", "crates/win_tree", "crates/cprs", "crates/threadpool"]
