[package]
name = "filemove_r"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
threadpool = { version = "0.1.0", path = "../threadpool" }
win_tree = { version = "0.1.3", path = "../win_tree" }
